/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as HowRouteImport } from './routes/how'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as MarketRouteImport } from './routes/market'
import { Route as CardIdRouteImport } from './routes/card.$id'
import { Route as CollectorIdRouteImport } from './routes/collector.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const CardIdRoute = CardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorIdRoute = CollectorIdRouteImport.update({
  id: '/collector/$id',
  path: '/collector/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/how': typeof HowRoute
  '/locker': typeof LockerRoute
  '/market': typeof MarketRoute
  '/card/$id': typeof CardIdRoute
  '/collector/$id': typeof CollectorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/how': typeof HowRoute
  '/locker': typeof LockerRoute
  '/market': typeof MarketRoute
  '/card/$id': typeof CardIdRoute
  '/collector/$id': typeof CollectorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/activity': typeof ActivityRoute
  '/how': typeof HowRoute
  '/locker': typeof LockerRoute
  '/market': typeof MarketRoute
  '/card/$id': typeof CardIdRoute
  '/collector/$id': typeof CollectorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/activity'
    | '/how'
    | '/locker'
    | '/market'
    | '/card/$id'
    | '/collector/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/activity'
    | '/how'
    | '/locker'
    | '/market'
    | '/card/$id'
    | '/collector/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/activity'
    | '/how'
    | '/locker'
    | '/market'
    | '/card/$id'
    | '/collector/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ActivityRoute: typeof ActivityRoute
  HowRoute: typeof HowRoute
  LockerRoute: typeof LockerRoute
  MarketRoute: typeof MarketRoute
  CardIdRoute: typeof CardIdRoute
  CollectorIdRoute: typeof CollectorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$id': {
      id: '/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof CardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/$id': {
      id: '/collector/$id'
      path: '/collector/$id'
      fullPath: '/collector/$id'
      preLoaderRoute: typeof CollectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ActivityRoute: ActivityRoute,
  HowRoute: HowRoute,
  LockerRoute: LockerRoute,
  MarketRoute: MarketRoute,
  CardIdRoute: CardIdRoute,
  CollectorIdRoute: CollectorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
